# Drupal with PostgreSQL
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
#
# During initial Drupal setup,
# Database type: PostgreSQL
# Database name: postgres
# Database username: postgres
# Database password: example
# ADVANCED OPTIONS; Database host: postgres

version: '3.1'

services:

  drupal:
  # imagem drupal oficial com drupal 8.8.2 e apache
    image: vinihss/teste-drupal
    ports:
      - 8080:80
    environment:
      APACHE_RUN_GROUP: staff
    depends_on:
      - mysql
    volumes:
      #- ./bkp:/tmp/bkp
      - ./docroot/custom/:/var/www/html/modules/custom
      #- ./docroot/html/:/var/www/html/
      #- ./docroot/modules:/var/www/html/modules
      #- ./docroot/sites:/var/www/html/sites
    links:
      - "mysql"
    restart: always

  mysql:
    image: mysql:5.7
    volumes:
      - ./bkp:/tmp/bkp
      - ./data/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_ROOT_PASSWORD: drupal
    restart: always